llm:
  google:
    provider: "google"
    model_name: "gemini-1.5-pro"
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"

llm:
  provider: "openai"  
  model_name: "gpt-4"
  temperature: 0.7
  max_tokens: 500
  top_p: 1.0

